version: '3.8'

x-common-variables: &common-variables
  MYSQL_DATABASE: books
  MYSQL_USER: MYSQL_USER
  MYSQL_PASSWORD: MYSQL_PASSWORD

services:
  mongo_db:
    container_name: db_container
    image: mongo:latest
    restart: always
    
    volumes:
      - mongo_db:/data/db
    
    

  nginx:
    depends_on:
      - api
      - client
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "3050:80"

  api:
    build: "./server" 
    
    
    ports:
      - 4000:3000

    environment:
        PORT: 3000
        MONGODB_URI: mongodb://127.0.0.1:27017/TechDB

    depends_on:
      - mongo_db

  client:
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      dockerfile: Dockerfile
      context: ./client
    volumes:
      - /client/node_modules
      - ./client:/client

  adminer:
      image: adminer:latest
      restart: unless-stopped
      ports:
        - 8000:8080
      depends_on:
        - mongo_db
      environment:
        ADMINER_DEFAULT_SERVER: mongo_db

volumes:
  mongo_db: {}